name: firebase_tests
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5
  firebase_remote_config: ^4.2.5
  cloud_firestore: ^4.9.0
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
